(function ($) {
  Drupal.behaviors.qconbs = {
    attach: function (context, settings) {
        "use strict";
        window.addEventListener('scroll', function(e){
            var distanceY = window.pageYOffset || document.documentElement.scrollTop,
                shrinkOn = 200,   // How many pixels does the window have to scroll before the header shrinks
                header = $(".qcon-base-top");
            if (distanceY > shrinkOn) {
                header.addClass("smaller");
            } else {
                if (header.hasClass("smaller")) {
                    header.removeClass("smaller");
                }
            }
        });
        
        //initialize eqHegth
        $('.views-field.views-field-field-image-speaker-bio').eqHeight();

        $('.past-years-flex-align').eqHeight('.panel');
        
        $('#views-bootstrap-carousel-1').on('slide.bs.carousel', function () {
          $(window).resize();
        })
        
        
    }
  };
})(jQuery);;
// Generated by CoffeeScript 1.4.0
/*
eqHeight.coffee v1.2.8
http://jsliang.github.com/eqHeight.coffee

Copyright (c) 2013, Jui-Shan Liang <jenny@jsliang.com>
All rights reserved.
Licensed under GPL v2.
*/(function(){var e;e=jQuery;e.fn.extend({eqHeight:function(t,n){var r;n==null&&(n={equalize_interval:null});r=null;return this.each(function(){var i,s,o,u,a;i=e(this).find(t);i.length===0&&(i=e(this).children(t));if(i.length===0)return;a=function(){var t,n;t=e(".eqHeight_row");n=0;t.each(function(){return n=Math.max(e(this).height(),n)});t.height(n);return e(".eqHeight_row").removeClass("eqHeight_row")};s=function(){var t;i.height("auto");t=i.first().position().top;i.each(function(){var n;n=e(this).position().top;if(n!==t){a();t=e(this).position().top}return e(this).addClass("eqHeight_row")});return a()};u=function(){clearTimeout(r);return r=setTimeout(s,100)};o=function(){s();return r=setTimeout(o,n.equalize_interval)};e(window).load(s);return typeof n.equalize_interval=="number"?o():e(window).resize(u)})}})}).call(this);;
